#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread Configuration */

/* RT-Thread Kernel */

#define RT_NAME_MAX 8
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 1000
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 256
#define RT_DEBUG

/* Inter-Thread communication */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE

/* Memory Management */

#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_HEAP

/* Kernel Device Object */

#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE 128
#define RT_CONSOLE_DEVICE_NAME "uart3"
#define RT_VER_NUM 0x30105
#define ARCH_ARM
#define RT_USING_CPU_FFS
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M3

/* RT-Thread Components */

#define RT_USING_COMPONENTS_INIT
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048
#define RT_MAIN_THREAD_PRIORITY 10

/* C++ features */


/* Command shell */

#define RT_USING_FINSH
#define FINSH_THREAD_NAME "tshell"
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define FINSH_USING_SYMTAB
#define FINSH_USING_DESCRIPTION
#define FINSH_THREAD_PRIORITY 20
#define FINSH_THREAD_STACK_SIZE 1024
#define FINSH_CMD_SIZE 80
#define FINSH_USING_MSH
#define FINSH_USING_MSH_DEFAULT
#define FINSH_USING_MSH_ONLY
#define FINSH_ARG_MAX 10

/* Device virtual file system */

#define RT_USING_DFS
#define DFS_USING_WORKDIR
#define DFS_FILESYSTEMS_MAX 2
#define DFS_FILESYSTEM_TYPES_MAX 2
#define DFS_FD_MAX 16
#define RT_USING_DFS_ELMFAT

/* elm-chan's FatFs, Generic FAT Filesystem Module */

#define RT_DFS_ELM_CODE_PAGE 437
#define RT_DFS_ELM_WORD_ACCESS
#define RT_DFS_ELM_USE_LFN_0
#define RT_DFS_ELM_USE_LFN 0
#define RT_DFS_ELM_MAX_LFN 255
#define RT_DFS_ELM_DRIVES 2
#define RT_DFS_ELM_MAX_SECTOR_SIZE 512
#define RT_USING_DFS_DEVFS
#define RT_USING_DFS_UFFS
#define RT_UFFS_ECC_MODE_1
#define RT_UFFS_ECC_MODE 1
#define RT_USING_DFS_JFFS2

/* Device Drivers */

#define RT_USING_DEVICE_IPC
#define RT_PIPE_BUFSZ 512
#define RT_USING_SYSTEM_WORKQUEUE
#define RT_SYSTEM_WORKQUEUE_STACKSIZE 2048
#define RT_SYSTEM_WORKQUEUE_PRIORITY 23
#define RT_USING_SERIAL
#define RT_SERIAL_USING_DMA
#define RT_SERIAL_RB_BUFSZ 64
#define RT_USING_I2C
#define RT_USING_I2C_BITOPS
#define RT_USING_PIN
#define RT_USING_ADC
#define RT_USING_MTD_NOR
#define RT_USING_MTD_NAND
//#define RT_USING_RTC
#define RT_USING_SDIO
#define RT_SDIO_STACK_SIZE 512
#define RT_SDIO_THREAD_PRIORITY 15
#define RT_MMCSD_STACK_SIZE 1024
#define RT_MMCSD_THREAD_PREORITY 22
#define RT_MMCSD_MAX_PARTITION 16
#define RT_USING_SPI
#define RT_USING_SFUD
#define RT_SFUD_USING_SFDP
#define RT_SFUD_USING_FLASH_INFO_TABLE
#define RT_SFUD_SPI_MAX_HZ 50000000
#define RT_USING_WDT
#define RT_USING_SENSOR
#define RT_USING_SENSOR_CMD

/* Using USB */


/* POSIX layer and C standard library */

#define RT_USING_LIBC
#define RT_USING_POSIX
//#define RT_USING_POSIX_TERMIOS

/* Network */

/* Socket abstraction layer */

#define RT_USING_SAL

/* protocol stack implement */

#define SAL_USING_AT
#define SAL_USING_TLS
#define SAL_USING_POSIX

/* Network interface device */

#define RT_USING_NETDEV
#define NETDEV_USING_IFCONFIG
#define NETDEV_USING_PING
#define NETDEV_USING_NETSTAT
#define NETDEV_IPV4 1
#define NETDEV_IPV6 0

/* light weight TCP/IP stack */


/* AT commands */

#define RT_USING_AT
#define AT_USING_CLIENT
#define AT_CLIENT_NUM_MAX 1
#define AT_USING_SOCKET
#define AT_USING_CLI
#define AT_CMD_MAX_LEN 128
#define AT_SW_VERSION_NUM 0x10300

/* VBUS(Virtual Software BUS) */


/* Utilities */

#define RT_USING_RYM

/* RT-Thread online packages */

/* IoT - internet of things */

#define PKG_USING_PAHOMQTT
#define PAHOMQTT_PIPE_MODE
#define RT_PKG_MQTT_THREAD_STACK_SIZE 4096
#define PKG_PAHOMQTT_SUBSCRIBE_HANDLERS 1
#define MQTT_DEBUG
#define PKG_USING_PAHOMQTT_V110
#define PKG_USING_WEBCLIENT
#define WEBCLIENT_NOT_USE_TLS
#define PKG_USING_WEBCLIENT_V212
#define PKG_WEBCLIENT_VER_NUM 0x20102
#define PKG_USING_LIBMODBUS
#define PKG_USING_LIBMODBUS_LATEST_VERSION
#define PKG_LIBMODBUS_VER_NUM 0x99999

/* Wi-Fi */

/* Marvell WiFi */


/* Wiced WiFi */

#define PKG_USING_AT_DEVICE
#define AT_DEVICE_USING_SIM76XX
#define AT_DEVICE_SIM76XX_SAMPLE
#define SIM76XX_SAMPLE_POWER_PIN -1
#define SIM76XX_SAMPLE_STATUS_PIN -1
#define SIM76XX_SAMPLE_CLIENT_NAME "uart2"
#define SIM76XX_SAMPLE_RECV_BUFF_LEN 512
#define PKG_USING_AT_DEVICE_V203
#define PKG_AT_DEVICE_VER_NUM 0x20003

/* IoT Cloud */

#define PKG_USING_OTA_DOWNLOADER
#define PKG_USING_YMODEM_OTA
#define PKG_USING_OTA_DOWNLOADER_LATEST_VERSION
#define PKG_USING_LIBCURL2RTT
#define PKG_USING_LIBCURL2RTT_V076700

/* security packages */

#define PKG_USING_MBEDTLS

/* Select Root Certificate */

#define MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_ECP_WINDOW_SIZE 2
#define MBEDTLS_SSL_MAX_CONTENT_LEN 3584
#define MBEDTLS_MPI_MAX_SIZE 1024
#define MBEDTLS_CTR_DRBG_KEYSIZE 32
#define PKG_USING_MBEDTLS_V2710

/* language packages */

#define PKG_USING_LUA
#define PKG_USING_LUA_V100
#define LUA_USING_PORTING_V514

/* multimedia packages */


/* tools packages */

#define PKG_USING_QRCODE
#define PKG_QRCODE_SAMPLE
#define PKG_USING_QRCODE_LATEST_VERSION

/* system packages */

#define PKG_USING_FAL
#define FAL_DEBUG 0
#define FAL_PART_HAS_TABLE_CFG
#define FAL_USING_SFUD_PORT
#define FAL_USING_NOR_FLASH_DEV_NAME "W25Q256"
#define PKG_USING_FAL_V00500
#define PKG_FAL_VER_NUM 0x00500
#define PKG_USING_FLASHDB
#define FDB_USING_KVDB
#define FDB_USING_TSDB
#define FDB_WRITE_GRAN_1BIT
#define FDB_WRITE_GRAN 1
#define FLASHDB_USING_SAMPLES
#define FDB_DEBUG_ENABLE
#define PKG_USING_FLASHDB_V10000
#define PKG_USING_SQLITE
#define PKG_SQLITE_SQL_MAX_LEN 1024
#define PKG_SQLITE_DB_NAME_MAX_LEN 64
#define PKG_SQLITE_DAO_EXAMPLE
#define PKG_USING_SQLITE_V3193
#define PKG_USING_DFS_YAFFS
#define PKG_USING_YAFFS_LATEST_VERSION
#define PKG_USING_SYSWATCH
#define SYSWATCH_EXCEPT_RESOLVE_MODE_2
#define SYSWATCH_EXCEPT_RESOLVE_MODE 2
#define SYSWATCH_EXCEPT_TIMEOUT 60
#define SYSWATCH_EXCEPT_CONFIRM_TMO 15
#define SYSWATCH_EXCEPT_RESUME_DLY 15
#define SYSWATCH_THREAD_PRIO 0
#define SYSWATCH_THREAD_STK_SIZE 512
#define SYSWATCH_THREAD_NAME "syswatch"
#define SYSWATCH_WDT_NAME "wdt"
#define SYSWATCH_WDT_TIMEOUT 5
#define PKG_USING_SYSWATCH_LATEST_VERSION
#define PKG_USING_MININI
#define PKG_USING_MININI_V120
#define PKG_USING_QBOOT
#define QBOOT_APP_PART_NAME "app"
#define QBOOT_DOWNLOAD_PART_NAME "download"
#define QBOOT_FACTORY_PART_NAME "factory"
#define QBOOT_USING_QUICKLZ
#define QBOOT_USING_SHELL
#define QBOOT_SHELL_KEY_CHK_TMO 5
#define QBOOT_USING_SYSWATCH
#define QBOOT_USING_OTA_DOWNLOADER
#define QBOOT_USING_PRODUCT_INFO
#define QBOOT_PRODUCT_NAME "Qboot test device"
#define QBOOT_PRODUCT_VER "v1.00 2020.07.27"
#define QBOOT_PRODUCT_MCU "stm32l4r5zi"
#define QBOOT_USING_STATUS_LED
#define QBOOT_STATUS_LED_PIN 0
#define QBOOT_STATUS_LED_LEVEL 1
#define QBOOT_THREAD_STK_SIZE 4096
#define QBOOT_THREAD_PRIO 5
#define PKG_USING_QBOOT_LATEST_VERSION

/* peripheral libraries and drivers */

#define PKG_USING_SENSORS_DRIVERS
#define PKG_USING_SHTC1
#define PKG_USING_SHTC1_LATEST_VERSION
#define PKG_USING_MAX6675
#define PKG_USING_MAX6675_LATEST_VERSION
#define PKG_USING_BUTTON
#define SINGLE_AND_DOUBLE_TRIGGER
#define LONG_FREE_TRIGGER
#define BUTTON_DEBOUNCE_TIME 2
#define BUTTON_CONTINUOS_CYCLE 1
#define BUTTON_LONG_CYCLE 1
#define BUTTON_DOUBLE_TIME 15
#define BUTTON_LONG_TIME 50
#define PKG_USING_BUTTON_V101
#define PKG_USING_SIGNAL_LED
#define PKG_USING_SIGNAL_LED_LATEST_VERSION

/* signalLed Options */

#define SIGNAL_LED_USING_SAMPLE
#define PKG_USING_LEDBLINK
#define PKG_USING_LEDBLINK_LATEST_VERSION
#define PKG_USING_LITTLED
#define PKG_USING_LITTLED_PERIOD 1000
#define PKG_USING_LITTLED_PULSE 500
#define PKG_USING_LITTLED_BELL_TIME 50000
#define PKG_USING_LITTLED_BEEP_COUNT 3
#define PKG_USING_LITTLED_SAMPLE
#define PKG_USING_LITTLED_LATEST_VERSION
#define PKG_USING_INFRARED

/* Select infrared decoder */

#define PKG_USING_DRV_INFRARED
#define INFRARED_SEND
#define INFRARED_SEND_PWM "pwm4"
#define INFRARED_PWM_DEV_CHANNEL 3
#define INFRARED_SEND_HWTIMER "timer15"
#define INFRARED_MAX_SEND_SIZE 1000
#define INFRARED_RECEIVE
#define INFRARED_RECEIVE_PIN 17
#define INFRARED_RECEIVE_HWTIMER "timer16"
#define PKG_USING_INFRARED_LATEST_VERSION
#define PKG_USING_PCA9685
#define PKG_USING_PCA9685_LATEST_VERSION
#define PKG_USING_I2C_TOOLS
#define PKG_USING_I2C_TOOLS_LATEST_VERSION
#define PKG_USING_BEEP
#define PKG_BEEP_ACTIVE_BUZZER
#define PKG_BEEP_USING_MSH_CMD
#define PKG_BEEP_THREAD_STACK_USING_HEAP
#define PKG_USING_BEEP_V110
#define PKG_USING_EASYBLINK
#define PKG_EASYBLINK_MAX_LED_NUMS 1
#define PKG_EASYBLINK_USING_MSH_CMD
#define PKG_EASYBLINK_USING_MUTEX
#define PKG_EASYBLINK_USING_HEAP
#define PKG_USING_EASYBLINK_V201
#define PKG_USING_QLED
#define QLED_TOTAL 5
#define QLED_TIME_UNIT_MS 10
#define QLED_THREAD_NAME "qled"
#define QLED_THREAD_STACK_SIZE 512
#define QLED_THREAD_PRIO 3
#define QLED_USING_SAMPLE
#define QLED_RUN_PIN -1
#define QLED_SOS_PIN -1
#define PKG_USING_QLED_V100

/* miscellaneous packages */

#define PKG_USING_FASTLZ
#define PKG_USING_FASTLZ_V101
#define PKG_USING_QUICKLZ
#define QLZ_COMPRESSION_LEVEL 3
#define PKG_USING_QUICKLZ_V101
#define PKG_USING_MULTIBUTTON
#define PKG_USING_MULTIBUTTON_V102

/* MultiButton Options */

#define PKG_USING_FLEXIBLE_BUTTON
#define PKG_USING_FLEXIBLE_BUTTON_V100
#define PKG_USING_DIGITALCTRL
#define PKG_USING_DIGITALCTRL_LATEST_VERSION
#define PKG_USING_UPARAM
#define PKG_USING_UPARAM_LATEST_VERSION

/* samples: kernel and components samples */

#define PKG_USING_KERNEL_SAMPLES
#define PKG_USING_KERNEL_SAMPLES_V030
#define PKG_USING_FILESYSTEM_SAMPLES
#define PKG_USING_FILESYSTEM_SAMPLES_V020
#define PKG_USING_NETWORK_SAMPLES
#define PKG_USING_NETWORK_SAMPLES_V030
#define PKG_USING_PERIPHERAL_SAMPLES
#define PKG_USING_PERIPHERAL_SAMPLES_V040
#define PKG_USING_CRCLIB
#define CRCLIB_USING_CRC8
#define CRC8_USING_CONST_TABLE
#define CRC8_POLY_8C
#define CRC8_POLY 0x8C
#define CRCLIB_USING_CRC16
#define CRC16_USING_CONST_TABLE
#define CRC16_POLY_A001
#define CRC16_POLY 0xA001
#define CRCLIB_USING_CRC32
#define CRC32_USING_CONST_TABLE
#define CRC32_POLY_EDB88320
#define CRC32_POLY 0xEDB88320
#define PKG_USING_CRCLIB_V100
#define SOC_FAMILY_STM32
#define SOC_SERIES_STM32F1

/* Hardware Drivers Config */

#define SOC_STM32F103RG

/* Onboard Peripheral Drivers */

#define BSP_USING_SDIO_SDCARD

/* On-chip Peripheral Drivers */

#define BSP_USING_GPIO
#define BSP_USING_UART
#define BSP_USING_UART2
#define BSP_USING_UART3
#define BSP_USING_ADC
#define BSP_USING_ADC1
#define BSP_USING_SDIO
#define BSP_USING_ON_CHIP_FLASH

/* Board extended module Drivers */


#endif
